[package]
name = "howtodo-usejanggab"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
janggab = { version = "0.1.0", path = "../../crates/janggab" }
janggab-core = { version = "0.1.0", path = "../../crates/janggab-core" }
